Scaling roc
epic-open-source/seismometer pull request #125
Opened 2024-12-31 16:40 UTC by diehlbw

# Overview

Closes #124 

## Description of changes
Changed model evaluation code (binary classifiers) to scale the threshold info for ROC annotations

## Author Checklist
- [ ] Linting passes; run early with [pre-commit hook](https://pre-commit.com/#install).
- [ ] Tests added for new code and issue being fixed.
- [ ] Added type annotations and full numpy-style docstrings for new methods.
- [ ] Draft your news fragment in new `changelog/ISSUE.TYPE.rst` files; see [changelog/README.md](https://github.com/epic-open-source/seismometer/blob/main/changelog/README.md).

2025-01-02 16:28 UTC, gbowlin commented on src/seismometer/plot/mpl/binary_classifier.py
> +    roc_thresholds = roc_data["Threshold"]
Can you add a comment to ci_data to include something about the ROC data? It feels like that should be fixed to a normalized format, sicne Threshold could be percentage or precentile.

2025-01-02 16:31 UTC, gbowlin commented on src/seismometer/plot/mpl/binary_classifier.py
> +    if not (roc_thresholds[2:] > 2).any():
```suggestion
    if not (roc_thresholds[2:] > 1).any():
```

1.5 is also greater than 1, at the very least `>=2` to make sure we catch that edge case.

2025-01-02 16:34 UTC, gbowlin requested changes
Can we move the implicit formatting check out, and do a discrete check instead?

2025-01-02 18:41 UTC, diehlbw commented on src/seismometer/plot/mpl/binary_classifier.py
> +    if not (roc_thresholds[2:] > 2).any():
Updated.  This method was due to _old_ sklearn behavior, and the slicing skips that insertion regardless of value.

2025-01-02 20:00 UTC, diehlbw commented on src/seismometer/plot/mpl/binary_classifier.py
> +    roc_thresholds = roc_data["Threshold"]
Moved the logic into the ci calculation, and reused the as_percentages method that binary_stats does

2025-01-02 20:01 UTC, diehlbw commented on src/seismometer/plot/mpl/binary_classifier.py
> +    if not (roc_thresholds[2:] > 2).any():
And then deleted...

2025-01-02 21:01 UTC, gbowlin commented on src/seismometer/plot/mpl/_lines.py
> +        Index of line being annotated in order to match color, by default 0.
I think you can now remove

2025-01-02 21:01 UTC, gbowlin commented on src/seismometer/plot/mpl/_lines.py
> +        Index of line being annotated in order to match color, by default 0.
![image](https://github.com/user-attachments/assets/33e60aba-95e5-47c9-8196-30c680b6fbab)

2025-01-02 21:50 UTC, diehlbw commented on src/seismometer/plot/mpl/_lines.py
> +        Index of line being annotated in order to match color, by default 0.
Annoyingly... this is not the case.  
This instance isn't about scores nor roc_info, it's around the thresholds being labeled.  In our examples this is the 0.2 and 0.8 that are displayed as 20 and 80.

Added a comment https://github.com/epic-open-source/seismometer/issues/51#issuecomment-2568417887 to improve this alongside making score bounds more discrete, which I assume will include scaling on load.
Also made these functions private to limit usage with the possibility that they will change dramatically alongside that enhancement.

2025-01-03 15:02 UTC, gbowlin commented on src/seismometer/data/performance.py
> +    force_percentages : bool, optional
Should we add a unit test for this use case?

2025-01-03 15:03 UTC, gbowlin reviewed
Looks fine, can we add a unit test around forcing precents?

2025-01-06 16:29 UTC, gbowlin approved these changes

2025-01-06 17:05 UTC, merged